from graphlibpy import Graph

g = Graph()
n1 = g.add_node("test")
n2 = g.add_node("test2")
e = g.add_edge("test", "test2", 5)
g.add_node("a")
g.add_node("b")
g.add_edge("a", "b", 1)
g.add_edge("b", "test", 8)
g.add_edge("test", "a", 0)
print(n1.label)
print(e)
print(g.nodes)
print(g.edges)
print(g.neighbours("test"))
print(g.get_edge("test", "test2"))
print(g.order)
print(g.size)
print(g.is_empty)
print(g.dijkstra("a"))
print(g.bfs("test"))
print(g.dfs("test"))
