[package]
name = "graphlibpy"
version = "0.1.0"
edition = "2021"

[lib]
name = "graphlibpy"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.3", features = ["extension-module"] }

[workspace]
